#!/bin/sh

ARCHS="armeabi armeabi-v7a arm64-v8a x86 x86_64 mips mips64"

BUILDOUT="build-out"
JNILIBS="$BUILDOUT/jniLibs"
LIBS="$BUILDOUT/libs" 
INCS="$BUILDOUT/include" 

# directories
SOURCE="../../tensorflow"

COMPILE="y"

if [ "$*" ]
then
	ARCHS="$*"
fi

if [ "$COMPILE" ]
then
	CWD=`pwd`
	for ARCH in $ARCHS
	do
		if [ "$ARCH" = "armeabi" -o "$ARCH" = "armeabi-v7a" \
             -o "$ARCH" = "arm64-v8a" -o "$ARCH" = "x86" \
            -o "$ARCH" = "x86_64" -o "$ARCH" = "mips" -o "$ARCH" = "mips64" ]
        then

		    echo "building $ARCH..."
            #echo "$CWD/$JNILIBS/$ARCH"
            if [ -d "$CWD/$JNILIBS/$ARCH" ]
            then
		        rm -rf  "$CWD/$JNILIBS/$ARCH" 
		        mkdir -p "$CWD/$JNILIBS/$ARCH"
            else
		        mkdir -p "$CWD/$JNILIBS/$ARCH"
            fi

            cd $SOURCE
            git checkout v2.0.0-alpha0 -b v2.0.0-alpha0
            bazel clean
		    bazel build --cxxopt='--std=c++11' \
                      //tensorflow/lite/java:tensorflowlite --crosstool_top=//external:android/crosstool \
                      --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --cpu=$ARCH

		    cd $CWD
            echo "cp $ARCH/libtensorflowlite_jni.so"
            cp "$CWD/$SOURCE/bazel-bin/tensorflow/lite/java/libtensorflowlite_jni.so" "$CWD/$JNILIBS/$ARCH"

        fi
    done
fi


echo "cp libtensorflowlite.jar..."
if [ -d "$CWD/$LIBS" ]
then
	rm -rf "$CWD/$LIBS" 
	mkdir -p "$CWD/$LIBS"
else
	mkdir -p "$CWD/$LIBS"
fi
#echo "$SOURCE/bazel-bin/tensorflow/lite/java/libtensorflowlite.jar"
cp "$CWD/$SOURCE/bazel-bin/tensorflow/lite/java/libtensorflowlite.jar" "$CWD/$LIBS"

echo "cp headers..."
#if [ -d "$CWD/$INCS" ]
#then
#	rm -rf "$CWD/$INCS" 
#	mkdir -p "$CWD/$INCS"
#else
#	mkdir -p "$CWD/$INCS"
#fi
cp -r "$CWD/$SOURCE/tensorflow/lite/tools/make/downloads/flatbuffers/include/flatbuffers" "$CWD/$INCS"

cp "$CWD/$SOURCE/tensorflow/lite/kernels/activation_functor.h" "$CWD/$INCS/tensorflow/lite/kernels/activation_functor.h"
cp "$CWD/$SOURCE/tensorflow/lite/kernels/kernel_util.h" "$CWD/$INCS/tensorflow/lite/kernels/kernel_util.h"
cp "$CWD/$SOURCE/tensorflow/lite/kernels/subgraph_test_util.h" "$CWD/$INCS/tensorflow/lite/kernels/subgraph_test_util.h"
cp "$CWD/$SOURCE/tensorflow/lite/kernels/lstm_eval.h" "$CWD/$INCS/tensorflow/lite/kernels/lstm_eval.h"
cp "$CWD/$SOURCE/tensorflow/lite/kernels/internal/compatibility.h" "$CWD/$INCS/tensorflow/lite/kernels/internal/compatibility.h"
cp "$CWD/$SOURCE/tensorflow/lite/kernels/internal/tensor_utils.h" "$CWD/$INCS/tensorflow/lite/kernels/internal/tensor_utils.h"
cp "$CWD/$SOURCE/tensorflow/lite/kernels/internal/mfcc.h" "$CWD/$INCS/tensorflow/lite/kernels/internal/mfcc.h"
cp "$CWD/$SOURCE/tensorflow/lite/kernels/internal/types.h" "$CWD/$INCS/tensorflow/lite/kernels/internal/types.h"
cp "$CWD/$SOURCE/tensorflow/lite/kernels/internal/round.h" "$CWD/$INCS/tensorflow/lite/kernels/internal/round.h"
cp "$CWD/$SOURCE/tensorflow/lite/kernels/internal/quantization_util.h" "$CWD/$INCS/tensorflow/lite/kernels/internal/quantization_util.h"
cp "$CWD/$SOURCE/tensorflow/lite/kernels/internal/mfcc_dct.h" "$CWD/$INCS/tensorflow/lite/kernels/internal/mfcc_dct.h"
cp "$CWD/$SOURCE/tensorflow/lite/kernels/internal/spectrogram.h" "$CWD/$INCS/tensorflow/lite/kernels/internal/spectrogram.h"
cp "$CWD/$SOURCE/tensorflow/lite/kernels/internal/common.h" "$CWD/$INCS/tensorflow/lite/kernels/internal/common.h"
cp "$CWD/$SOURCE/tensorflow/lite/kernels/internal/optimized/eigen_tensor_reduced_instantiations_google.h" "$CWD/$INCS/tensorflow/lite/kernels/internal/optimized/eigen_tensor_reduced_instantiations_google.h"
cp "$CWD/$SOURCE/tensorflow/lite/kernels/internal/optimized/optimized_ops.h" "$CWD/$INCS/tensorflow/lite/kernels/internal/optimized/optimized_ops.h"
cp "$CWD/$SOURCE/tensorflow/lite/kernels/internal/optimized/depthwiseconv_uint8.h" "$CWD/$INCS/tensorflow/lite/kernels/internal/optimized/depthwiseconv_uint8.h"
cp "$CWD/$SOURCE/tensorflow/lite/kernels/internal/optimized/depthwiseconv_uint8_transitional.h" "$CWD/$INCS/tensorflow/lite/kernels/internal/optimized/depthwiseconv_uint8_transitional.h"
cp "$CWD/$SOURCE/tensorflow/lite/kernels/internal/optimized/cpu_check.h" "$CWD/$INCS/tensorflow/lite/kernels/internal/optimized/cpu_check.h"
cp "$CWD/$SOURCE/tensorflow/lite/kernels/internal/optimized/depthwiseconv_float.h" "$CWD/$INCS/tensorflow/lite/kernels/internal/optimized/depthwiseconv_float.h"
cp "$CWD/$SOURCE/tensorflow/lite/kernels/internal/optimized/depthwiseconv_uint8_3x3_filter.h" "$CWD/$INCS/tensorflow/lite/kernels/internal/optimized/depthwiseconv_uint8_3x3_filter.h"
cp "$CWD/$SOURCE/tensorflow/lite/kernels/internal/optimized/multithreaded_conv.h" "$CWD/$INCS/tensorflow/lite/kernels/internal/optimized/multithreaded_conv.h"
cp "$CWD/$SOURCE/tensorflow/lite/kernels/internal/optimized/eigen_spatial_convolutions.h" "$CWD/$INCS/tensorflow/lite/kernels/internal/optimized/eigen_spatial_convolutions.h"
cp "$CWD/$SOURCE/tensorflow/lite/kernels/internal/optimized/eigen_tensor_reduced_instantiations_oss.h" "$CWD/$INCS/tensorflow/lite/kernels/internal/optimized/eigen_tensor_reduced_instantiations_oss.h"
cp "$CWD/$SOURCE/tensorflow/lite/kernels/internal/optimized/legacy_optimized_ops.h" "$CWD/$INCS/tensorflow/lite/kernels/internal/optimized/legacy_optimized_ops.h"
cp "$CWD/$SOURCE/tensorflow/lite/kernels/internal/optimized/tensor_utils_impl.h" "$CWD/$INCS/tensorflow/lite/kernels/internal/optimized/tensor_utils_impl.h"
cp "$CWD/$SOURCE/tensorflow/lite/kernels/internal/optimized/neon_tensor_utils.h" "$CWD/$INCS/tensorflow/lite/kernels/internal/optimized/neon_tensor_utils.h"
cp "$CWD/$SOURCE/tensorflow/lite/kernels/internal/mfcc_mel_filterbank.h" "$CWD/$INCS/tensorflow/lite/kernels/internal/mfcc_mel_filterbank.h"
cp "$CWD/$SOURCE/tensorflow/lite/kernels/internal/strided_slice_logic.h" "$CWD/$INCS/tensorflow/lite/kernels/internal/strided_slice_logic.h"
cp "$CWD/$SOURCE/tensorflow/lite/kernels/internal/tensor_ctypes.h" "$CWD/$INCS/tensorflow/lite/kernels/internal/tensor_ctypes.h"
cp "$CWD/$SOURCE/tensorflow/lite/kernels/internal/kernel_utils.h" "$CWD/$INCS/tensorflow/lite/kernels/internal/kernel_utils.h"
cp "$CWD/$SOURCE/tensorflow/lite/kernels/internal/legacy_types.h" "$CWD/$INCS/tensorflow/lite/kernels/internal/legacy_types.h"
cp "$CWD/$SOURCE/tensorflow/lite/kernels/internal/tensor.h" "$CWD/$INCS/tensorflow/lite/kernels/internal/tensor.h"
cp "$CWD/$SOURCE/tensorflow/lite/kernels/internal/reference/softmax.h" "$CWD/$INCS/tensorflow/lite/kernels/internal/reference/softmax.h"
cp "$CWD/$SOURCE/tensorflow/lite/kernels/internal/reference/legacy_reference_ops.h" "$CWD/$INCS/tensorflow/lite/kernels/internal/reference/legacy_reference_ops.h"
cp "$CWD/$SOURCE/tensorflow/lite/kernels/internal/reference/integer_ops/softmax.h" "$CWD/$INCS/tensorflow/lite/kernels/internal/reference/integer_ops/softmax.h"
cp "$CWD/$SOURCE/tensorflow/lite/kernels/internal/reference/integer_ops/dequantize.h" "$CWD/$INCS/tensorflow/lite/kernels/internal/reference/integer_ops/dequantize.h"
cp "$CWD/$SOURCE/tensorflow/lite/kernels/internal/reference/integer_ops/depthwise_conv.h" "$CWD/$INCS/tensorflow/lite/kernels/internal/reference/integer_ops/depthwise_conv.h"
cp "$CWD/$SOURCE/tensorflow/lite/kernels/internal/reference/integer_ops/logistic.h" "$CWD/$INCS/tensorflow/lite/kernels/internal/reference/integer_ops/logistic.h"
cp "$CWD/$SOURCE/tensorflow/lite/kernels/internal/reference/integer_ops/fully_connected.h" "$CWD/$INCS/tensorflow/lite/kernels/internal/reference/integer_ops/fully_connected.h"
cp "$CWD/$SOURCE/tensorflow/lite/kernels/internal/reference/integer_ops/add.h" "$CWD/$INCS/tensorflow/lite/kernels/internal/reference/integer_ops/add.h"
cp "$CWD/$SOURCE/tensorflow/lite/kernels/internal/reference/integer_ops/l2normalization.h" "$CWD/$INCS/tensorflow/lite/kernels/internal/reference/integer_ops/l2normalization.h"
cp "$CWD/$SOURCE/tensorflow/lite/kernels/internal/reference/integer_ops/log_softmax.h" "$CWD/$INCS/tensorflow/lite/kernels/internal/reference/integer_ops/log_softmax.h"
cp "$CWD/$SOURCE/tensorflow/lite/kernels/internal/reference/integer_ops/tanh.h" "$CWD/$INCS/tensorflow/lite/kernels/internal/reference/integer_ops/tanh.h"
cp "$CWD/$SOURCE/tensorflow/lite/kernels/internal/reference/integer_ops/mul.h" "$CWD/$INCS/tensorflow/lite/kernels/internal/reference/integer_ops/mul.h"
cp "$CWD/$SOURCE/tensorflow/lite/kernels/internal/reference/integer_ops/pooling.h" "$CWD/$INCS/tensorflow/lite/kernels/internal/reference/integer_ops/pooling.h"
cp "$CWD/$SOURCE/tensorflow/lite/kernels/internal/reference/integer_ops/conv.h" "$CWD/$INCS/tensorflow/lite/kernels/internal/reference/integer_ops/conv.h"
cp "$CWD/$SOURCE/tensorflow/lite/kernels/internal/reference/fully_connected.h" "$CWD/$INCS/tensorflow/lite/kernels/internal/reference/fully_connected.h"
cp "$CWD/$SOURCE/tensorflow/lite/kernels/internal/reference/depthwiseconv_uint8.h" "$CWD/$INCS/tensorflow/lite/kernels/internal/reference/depthwiseconv_uint8.h"
cp "$CWD/$SOURCE/tensorflow/lite/kernels/internal/reference/portable_tensor_utils.h" "$CWD/$INCS/tensorflow/lite/kernels/internal/reference/portable_tensor_utils.h"
cp "$CWD/$SOURCE/tensorflow/lite/kernels/internal/reference/depthwiseconv_float.h" "$CWD/$INCS/tensorflow/lite/kernels/internal/reference/depthwiseconv_float.h"
cp "$CWD/$SOURCE/tensorflow/lite/kernels/internal/reference/reference_ops.h" "$CWD/$INCS/tensorflow/lite/kernels/internal/reference/reference_ops.h"
cp "$CWD/$SOURCE/tensorflow/lite/kernels/internal/test_util.h" "$CWD/$INCS/tensorflow/lite/kernels/internal/test_util.h"
cp "$CWD/$SOURCE/tensorflow/lite/kernels/gemm_support.h" "$CWD/$INCS/tensorflow/lite/kernels/gemm_support.h"
cp "$CWD/$SOURCE/tensorflow/lite/kernels/register_ref.h" "$CWD/$INCS/tensorflow/lite/kernels/register_ref.h"
cp "$CWD/$SOURCE/tensorflow/lite/kernels/op_macros.h" "$CWD/$INCS/tensorflow/lite/kernels/op_macros.h"
cp "$CWD/$SOURCE/tensorflow/lite/kernels/eigen_support.h" "$CWD/$INCS/tensorflow/lite/kernels/eigen_support.h"
cp "$CWD/$SOURCE/tensorflow/lite/kernels/register.h" "$CWD/$INCS/tensorflow/lite/kernels/register.h"
cp "$CWD/$SOURCE/tensorflow/lite/kernels/test_util.h" "$CWD/$INCS/tensorflow/lite/kernels/test_util.h"
cp "$CWD/$SOURCE/tensorflow/lite/kernels/padding.h" "$CWD/$INCS/tensorflow/lite/kernels/padding.h"
cp "$CWD/$SOURCE/tensorflow/lite/context_util.h" "$CWD/$INCS/tensorflow/lite/context_util.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/micro/micro_interpreter.h" "$CWD/$INCS/tensorflow/lite/experimental/micro/micro_interpreter.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/micro/compatibility.h" "$CWD/$INCS/tensorflow/lite/experimental/micro/compatibility.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/micro/kernels/all_ops_resolver.h" "$CWD/$INCS/tensorflow/lite/experimental/micro/kernels/all_ops_resolver.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/micro/micro_mutable_op_resolver.h" "$CWD/$INCS/tensorflow/lite/experimental/micro/micro_mutable_op_resolver.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/micro/debug_log.h" "$CWD/$INCS/tensorflow/lite/experimental/micro/debug_log.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/micro/micro_error_reporter.h" "$CWD/$INCS/tensorflow/lite/experimental/micro/micro_error_reporter.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/micro/testing/test_utils.h" "$CWD/$INCS/tensorflow/lite/experimental/micro/testing/test_utils.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/micro/testing/micro_test.h" "$CWD/$INCS/tensorflow/lite/experimental/micro/testing/micro_test.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/micro/examples/micro_speech/no_1000ms_sample_data.h" "$CWD/$INCS/tensorflow/lite/experimental/micro/examples/micro_speech/no_1000ms_sample_data.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/micro/examples/micro_speech/yes_1000ms_sample_data.h" "$CWD/$INCS/tensorflow/lite/experimental/micro/examples/micro_speech/yes_1000ms_sample_data.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/micro/examples/micro_speech/audio_provider.h" "$CWD/$INCS/tensorflow/lite/experimental/micro/examples/micro_speech/audio_provider.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/micro/examples/micro_speech/command_responder.h" "$CWD/$INCS/tensorflow/lite/experimental/micro/examples/micro_speech/command_responder.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/micro/examples/micro_speech/yes_30ms_sample_data.h" "$CWD/$INCS/tensorflow/lite/experimental/micro/examples/micro_speech/yes_30ms_sample_data.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/micro/examples/micro_speech/feature_provider.h" "$CWD/$INCS/tensorflow/lite/experimental/micro/examples/micro_speech/feature_provider.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/micro/examples/micro_speech/CMSIS/sin_1k.h" "$CWD/$INCS/tensorflow/lite/experimental/micro/examples/micro_speech/CMSIS/sin_1k.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/micro/examples/micro_speech/CMSIS/hanning.h" "$CWD/$INCS/tensorflow/lite/experimental/micro/examples/micro_speech/CMSIS/hanning.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/micro/examples/micro_speech/no_30ms_sample_data.h" "$CWD/$INCS/tensorflow/lite/experimental/micro/examples/micro_speech/no_30ms_sample_data.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/micro/examples/micro_speech/micro_features/fft.h" "$CWD/$INCS/tensorflow/lite/experimental/micro/examples/micro_speech/micro_features/fft.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/micro/examples/micro_speech/micro_features/filterbank.h" "$CWD/$INCS/tensorflow/lite/experimental/micro/examples/micro_speech/micro_features/filterbank.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/micro/examples/micro_speech/micro_features/noise_reduction.h" "$CWD/$INCS/tensorflow/lite/experimental/micro/examples/micro_speech/micro_features/noise_reduction.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/micro/examples/micro_speech/micro_features/log_scale.h" "$CWD/$INCS/tensorflow/lite/experimental/micro/examples/micro_speech/micro_features/log_scale.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/micro/examples/micro_speech/micro_features/noise_reduction_util.h" "$CWD/$INCS/tensorflow/lite/experimental/micro/examples/micro_speech/micro_features/noise_reduction_util.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/micro/examples/micro_speech/micro_features/micro_features_generator.h" "$CWD/$INCS/tensorflow/lite/experimental/micro/examples/micro_speech/micro_features/micro_features_generator.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/micro/examples/micro_speech/micro_features/micro_model_settings.h" "$CWD/$INCS/tensorflow/lite/experimental/micro/examples/micro_speech/micro_features/micro_model_settings.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/micro/examples/micro_speech/micro_features/filterbank_util.h" "$CWD/$INCS/tensorflow/lite/experimental/micro/examples/micro_speech/micro_features/filterbank_util.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/micro/examples/micro_speech/micro_features/log_scale_util.h" "$CWD/$INCS/tensorflow/lite/experimental/micro/examples/micro_speech/micro_features/log_scale_util.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/micro/examples/micro_speech/micro_features/window.h" "$CWD/$INCS/tensorflow/lite/experimental/micro/examples/micro_speech/micro_features/window.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/micro/examples/micro_speech/micro_features/pcan_gain_control.h" "$CWD/$INCS/tensorflow/lite/experimental/micro/examples/micro_speech/micro_features/pcan_gain_control.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/micro/examples/micro_speech/micro_features/yes_micro_features_data.h" "$CWD/$INCS/tensorflow/lite/experimental/micro/examples/micro_speech/micro_features/yes_micro_features_data.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/micro/examples/micro_speech/micro_features/frontend.h" "$CWD/$INCS/tensorflow/lite/experimental/micro/examples/micro_speech/micro_features/frontend.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/micro/examples/micro_speech/micro_features/pcan_gain_control_util.h" "$CWD/$INCS/tensorflow/lite/experimental/micro/examples/micro_speech/micro_features/pcan_gain_control_util.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/micro/examples/micro_speech/micro_features/static_alloc.h" "$CWD/$INCS/tensorflow/lite/experimental/micro/examples/micro_speech/micro_features/static_alloc.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/micro/examples/micro_speech/micro_features/log_lut.h" "$CWD/$INCS/tensorflow/lite/experimental/micro/examples/micro_speech/micro_features/log_lut.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/micro/examples/micro_speech/micro_features/fft_util.h" "$CWD/$INCS/tensorflow/lite/experimental/micro/examples/micro_speech/micro_features/fft_util.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/micro/examples/micro_speech/micro_features/tiny_conv_micro_features_model_data.h" "$CWD/$INCS/tensorflow/lite/experimental/micro/examples/micro_speech/micro_features/tiny_conv_micro_features_model_data.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/micro/examples/micro_speech/micro_features/no_micro_features_data.h" "$CWD/$INCS/tensorflow/lite/experimental/micro/examples/micro_speech/micro_features/no_micro_features_data.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/micro/examples/micro_speech/micro_features/frontend_util.h" "$CWD/$INCS/tensorflow/lite/experimental/micro/examples/micro_speech/micro_features/frontend_util.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/micro/examples/micro_speech/micro_features/window_util.h" "$CWD/$INCS/tensorflow/lite/experimental/micro/examples/micro_speech/micro_features/window_util.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/micro/examples/micro_speech/micro_features/no_feature_data_slice.h" "$CWD/$INCS/tensorflow/lite/experimental/micro/examples/micro_speech/micro_features/no_feature_data_slice.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/micro/examples/micro_speech/micro_features/yes_feature_data_slice.h" "$CWD/$INCS/tensorflow/lite/experimental/micro/examples/micro_speech/micro_features/yes_feature_data_slice.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/micro/examples/micro_speech/micro_features/bits.h" "$CWD/$INCS/tensorflow/lite/experimental/micro/examples/micro_speech/micro_features/bits.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/micro/examples/micro_speech/recognize_commands.h" "$CWD/$INCS/tensorflow/lite/experimental/micro/examples/micro_speech/recognize_commands.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/micro/examples/micro_speech/simple_features/tiny_conv_simple_features_model_data.h" "$CWD/$INCS/tensorflow/lite/experimental/micro/examples/micro_speech/simple_features/tiny_conv_simple_features_model_data.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/micro/examples/micro_speech/simple_features/no_power_spectrum_data.h" "$CWD/$INCS/tensorflow/lite/experimental/micro/examples/micro_speech/simple_features/no_power_spectrum_data.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/micro/examples/micro_speech/simple_features/yes_power_spectrum_data.h" "$CWD/$INCS/tensorflow/lite/experimental/micro/examples/micro_speech/simple_features/yes_power_spectrum_data.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/micro/examples/micro_speech/simple_features/simple_features_generator.h" "$CWD/$INCS/tensorflow/lite/experimental/micro/examples/micro_speech/simple_features/simple_features_generator.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/micro/examples/micro_speech/simple_features/yes_simple_features_data.h" "$CWD/$INCS/tensorflow/lite/experimental/micro/examples/micro_speech/simple_features/yes_simple_features_data.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/micro/examples/micro_speech/simple_features/simple_model_settings.h" "$CWD/$INCS/tensorflow/lite/experimental/micro/examples/micro_speech/simple_features/simple_model_settings.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/micro/examples/micro_speech/simple_features/no_simple_features_data.h" "$CWD/$INCS/tensorflow/lite/experimental/micro/examples/micro_speech/simple_features/no_simple_features_data.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/micro/simple_tensor_allocator.h" "$CWD/$INCS/tensorflow/lite/experimental/micro/simple_tensor_allocator.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/micro/debug_log_numbers.h" "$CWD/$INCS/tensorflow/lite/experimental/micro/debug_log_numbers.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/kernels/ctc_beam_scorer.h" "$CWD/$INCS/tensorflow/lite/experimental/kernels/ctc_beam_scorer.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/kernels/ctc_loss_util.h" "$CWD/$INCS/tensorflow/lite/experimental/kernels/ctc_loss_util.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/kernels/top_n.h" "$CWD/$INCS/tensorflow/lite/experimental/kernels/top_n.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/kernels/ctc_beam_entry.h" "$CWD/$INCS/tensorflow/lite/experimental/kernels/ctc_beam_entry.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/kernels/ctc_decoder.h" "$CWD/$INCS/tensorflow/lite/experimental/kernels/ctc_decoder.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/kernels/ctc_beam_search.h" "$CWD/$INCS/tensorflow/lite/experimental/kernels/ctc_beam_search.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/writer/enum_mapping.h" "$CWD/$INCS/tensorflow/lite/experimental/writer/enum_mapping.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/writer/writer_lib.h" "$CWD/$INCS/tensorflow/lite/experimental/writer/writer_lib.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/microfrontend/lib/fft.h" "$CWD/$INCS/tensorflow/lite/experimental/microfrontend/lib/fft.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/microfrontend/lib/frontend_io.h" "$CWD/$INCS/tensorflow/lite/experimental/microfrontend/lib/frontend_io.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/microfrontend/lib/filterbank.h" "$CWD/$INCS/tensorflow/lite/experimental/microfrontend/lib/filterbank.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/microfrontend/lib/noise_reduction.h" "$CWD/$INCS/tensorflow/lite/experimental/microfrontend/lib/noise_reduction.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/microfrontend/lib/log_scale.h" "$CWD/$INCS/tensorflow/lite/experimental/microfrontend/lib/log_scale.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/microfrontend/lib/noise_reduction_util.h" "$CWD/$INCS/tensorflow/lite/experimental/microfrontend/lib/noise_reduction_util.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/microfrontend/lib/filterbank_util.h" "$CWD/$INCS/tensorflow/lite/experimental/microfrontend/lib/filterbank_util.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/microfrontend/lib/log_scale_util.h" "$CWD/$INCS/tensorflow/lite/experimental/microfrontend/lib/log_scale_util.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/microfrontend/lib/window.h" "$CWD/$INCS/tensorflow/lite/experimental/microfrontend/lib/window.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/microfrontend/lib/pcan_gain_control.h" "$CWD/$INCS/tensorflow/lite/experimental/microfrontend/lib/pcan_gain_control.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/microfrontend/lib/frontend.h" "$CWD/$INCS/tensorflow/lite/experimental/microfrontend/lib/frontend.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/microfrontend/lib/fft_io.h" "$CWD/$INCS/tensorflow/lite/experimental/microfrontend/lib/fft_io.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/microfrontend/lib/pcan_gain_control_util.h" "$CWD/$INCS/tensorflow/lite/experimental/microfrontend/lib/pcan_gain_control_util.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/microfrontend/lib/log_lut.h" "$CWD/$INCS/tensorflow/lite/experimental/microfrontend/lib/log_lut.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/microfrontend/lib/noise_reduction_io.h" "$CWD/$INCS/tensorflow/lite/experimental/microfrontend/lib/noise_reduction_io.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/microfrontend/lib/window_io.h" "$CWD/$INCS/tensorflow/lite/experimental/microfrontend/lib/window_io.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/microfrontend/lib/filterbank_io.h" "$CWD/$INCS/tensorflow/lite/experimental/microfrontend/lib/filterbank_io.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/microfrontend/lib/fft_util.h" "$CWD/$INCS/tensorflow/lite/experimental/microfrontend/lib/fft_util.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/microfrontend/lib/frontend_util.h" "$CWD/$INCS/tensorflow/lite/experimental/microfrontend/lib/frontend_util.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/microfrontend/lib/log_scale_io.h" "$CWD/$INCS/tensorflow/lite/experimental/microfrontend/lib/log_scale_io.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/microfrontend/lib/window_util.h" "$CWD/$INCS/tensorflow/lite/experimental/microfrontend/lib/window_util.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/microfrontend/lib/bits.h" "$CWD/$INCS/tensorflow/lite/experimental/microfrontend/lib/bits.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/objc/apis/TFLQuantizationParameters.h" "$CWD/$INCS/tensorflow/lite/experimental/objc/apis/TFLQuantizationParameters.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/objc/apis/TFLInterpreter.h" "$CWD/$INCS/tensorflow/lite/experimental/objc/apis/TFLInterpreter.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/objc/apis/TFLInterpreterOptions.h" "$CWD/$INCS/tensorflow/lite/experimental/objc/apis/TFLInterpreterOptions.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/objc/apis/TFLTensor.h" "$CWD/$INCS/tensorflow/lite/experimental/objc/apis/TFLTensor.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/objc/sources/TFLQuantizationParameters+Internal.h" "$CWD/$INCS/tensorflow/lite/experimental/objc/sources/TFLQuantizationParameters+Internal.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/objc/sources/TFLTensor+Internal.h" "$CWD/$INCS/tensorflow/lite/experimental/objc/sources/TFLTensor+Internal.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/objc/sources/TFLErrorUtil.h" "$CWD/$INCS/tensorflow/lite/experimental/objc/sources/TFLErrorUtil.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/objc/sources/TFLInterpreter+Internal.h" "$CWD/$INCS/tensorflow/lite/experimental/objc/sources/TFLInterpreter+Internal.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/c/c_api_experimental.h" "$CWD/$INCS/tensorflow/lite/experimental/c/c_api_experimental.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/c/c_api_internal.h" "$CWD/$INCS/tensorflow/lite/experimental/c/c_api_internal.h"
cp "$CWD/$SOURCE/tensorflow/lite/experimental/c/c_api.h" "$CWD/$INCS/tensorflow/lite/experimental/c/c_api.h"
cp "$CWD/$SOURCE/tensorflow/lite/version.h" "$CWD/$INCS/tensorflow/lite/version.h"
cp "$CWD/$SOURCE/tensorflow/lite/builtin_ops.h" "$CWD/$INCS/tensorflow/lite/builtin_ops.h"
cp "$CWD/$SOURCE/tensorflow/lite/core/subgraph.h" "$CWD/$INCS/tensorflow/lite/core/subgraph.h"
cp "$CWD/$SOURCE/tensorflow/lite/core/api/op_resolver.h" "$CWD/$INCS/tensorflow/lite/core/api/op_resolver.h"
cp "$CWD/$SOURCE/tensorflow/lite/core/api/error_reporter.h" "$CWD/$INCS/tensorflow/lite/core/api/error_reporter.h"
cp "$CWD/$SOURCE/tensorflow/lite/core/api/flatbuffer_conversions.h" "$CWD/$INCS/tensorflow/lite/core/api/flatbuffer_conversions.h"
cp "$CWD/$SOURCE/tensorflow/lite/op_resolver.h" "$CWD/$INCS/tensorflow/lite/op_resolver.h"
cp "$CWD/$SOURCE/tensorflow/lite/python/optimize/calibration_wrapper.h" "$CWD/$INCS/tensorflow/lite/python/optimize/calibration_wrapper.h"
cp "$CWD/$SOURCE/tensorflow/lite/python/interpreter_wrapper/interpreter_wrapper.h" "$CWD/$INCS/tensorflow/lite/python/interpreter_wrapper/interpreter_wrapper.h"
cp "$CWD/$SOURCE/tensorflow/lite/python/interpreter_wrapper/numpy.h" "$CWD/$INCS/tensorflow/lite/python/interpreter_wrapper/numpy.h"
cp "$CWD/$SOURCE/tensorflow/lite/python/interpreter_wrapper/python_error_reporter.h" "$CWD/$INCS/tensorflow/lite/python/interpreter_wrapper/python_error_reporter.h"
cp "$CWD/$SOURCE/tensorflow/lite/python/interpreter_wrapper/python_utils.h" "$CWD/$INCS/tensorflow/lite/python/interpreter_wrapper/python_utils.h"
cp "$CWD/$SOURCE/tensorflow/lite/string_util.h" "$CWD/$INCS/tensorflow/lite/string_util.h"
cp "$CWD/$SOURCE/tensorflow/lite/stderr_reporter.h" "$CWD/$INCS/tensorflow/lite/stderr_reporter.h"
cp "$CWD/$SOURCE/tensorflow/lite/allocation.h" "$CWD/$INCS/tensorflow/lite/allocation.h"
cp "$CWD/$SOURCE/tensorflow/lite/arena_planner.h" "$CWD/$INCS/tensorflow/lite/arena_planner.h"
cp "$CWD/$SOURCE/tensorflow/lite/interpreter.h" "$CWD/$INCS/tensorflow/lite/interpreter.h"
cp "$CWD/$SOURCE/tensorflow/lite/builtin_op_data.h" "$CWD/$INCS/tensorflow/lite/builtin_op_data.h"
cp "$CWD/$SOURCE/tensorflow/lite/memory_planner.h" "$CWD/$INCS/tensorflow/lite/memory_planner.h"
cp "$CWD/$SOURCE/tensorflow/lite/context.h" "$CWD/$INCS/tensorflow/lite/context.h"
cp "$CWD/$SOURCE/tensorflow/lite/java/src/main/native/nativeinterpreterwrapper_jni.h" "$CWD/$INCS/tensorflow/lite/java/src/main/native/nativeinterpreterwrapper_jni.h"
cp "$CWD/$SOURCE/tensorflow/lite/java/src/main/native/tensorflow_lite_jni.h" "$CWD/$INCS/tensorflow/lite/java/src/main/native/tensorflow_lite_jni.h"
cp "$CWD/$SOURCE/tensorflow/lite/java/src/main/native/tensor_jni.h" "$CWD/$INCS/tensorflow/lite/java/src/main/native/tensor_jni.h"
cp "$CWD/$SOURCE/tensorflow/lite/java/src/main/native/exception_jni.h" "$CWD/$INCS/tensorflow/lite/java/src/main/native/exception_jni.h"
cp "$CWD/$SOURCE/tensorflow/lite/java/src/main/native/init_tensorflow_jni.h" "$CWD/$INCS/tensorflow/lite/java/src/main/native/init_tensorflow_jni.h"
cp "$CWD/$SOURCE/tensorflow/lite/models/smartreply/predictor.h" "$CWD/$INCS/tensorflow/lite/models/smartreply/predictor.h"
cp "$CWD/$SOURCE/tensorflow/lite/simple_memory_arena.h" "$CWD/$INCS/tensorflow/lite/simple_memory_arena.h"
cp "$CWD/$SOURCE/tensorflow/lite/nnapi_delegate.h" "$CWD/$INCS/tensorflow/lite/nnapi_delegate.h"
cp "$CWD/$SOURCE/tensorflow/lite/error_reporter.h" "$CWD/$INCS/tensorflow/lite/error_reporter.h"
cp "$CWD/$SOURCE/tensorflow/lite/testing/tf_driver.h" "$CWD/$INCS/tensorflow/lite/testing/tf_driver.h"
cp "$CWD/$SOURCE/tensorflow/lite/testing/parse_testdata.h" "$CWD/$INCS/tensorflow/lite/testing/parse_testdata.h"
cp "$CWD/$SOURCE/tensorflow/lite/testing/test_runner.h" "$CWD/$INCS/tensorflow/lite/testing/test_runner.h"
cp "$CWD/$SOURCE/tensorflow/lite/testing/string_util.h" "$CWD/$INCS/tensorflow/lite/testing/string_util.h"
cp "$CWD/$SOURCE/tensorflow/lite/testing/tflite_diff_util.h" "$CWD/$INCS/tensorflow/lite/testing/tflite_diff_util.h"
cp "$CWD/$SOURCE/tensorflow/lite/testing/tokenize.h" "$CWD/$INCS/tensorflow/lite/testing/tokenize.h"
cp "$CWD/$SOURCE/tensorflow/lite/testing/message.h" "$CWD/$INCS/tensorflow/lite/testing/message.h"
cp "$CWD/$SOURCE/tensorflow/lite/testing/generate_testspec.h" "$CWD/$INCS/tensorflow/lite/testing/generate_testspec.h"
cp "$CWD/$SOURCE/tensorflow/lite/testing/join.h" "$CWD/$INCS/tensorflow/lite/testing/join.h"
cp "$CWD/$SOURCE/tensorflow/lite/testing/kernel_test/diff_analyzer.h" "$CWD/$INCS/tensorflow/lite/testing/kernel_test/diff_analyzer.h"
cp "$CWD/$SOURCE/tensorflow/lite/testing/kernel_test/input_generator.h" "$CWD/$INCS/tensorflow/lite/testing/kernel_test/input_generator.h"
cp "$CWD/$SOURCE/tensorflow/lite/testing/kernel_test/util.h" "$CWD/$INCS/tensorflow/lite/testing/kernel_test/util.h"
cp "$CWD/$SOURCE/tensorflow/lite/testing/util.h" "$CWD/$INCS/tensorflow/lite/testing/util.h"
cp "$CWD/$SOURCE/tensorflow/lite/testing/init_tensorflow.h" "$CWD/$INCS/tensorflow/lite/testing/init_tensorflow.h"
cp "$CWD/$SOURCE/tensorflow/lite/testing/tflite_driver.h" "$CWD/$INCS/tensorflow/lite/testing/tflite_driver.h"
cp "$CWD/$SOURCE/tensorflow/lite/testing/tflite_diff_flags.h" "$CWD/$INCS/tensorflow/lite/testing/tflite_diff_flags.h"
cp "$CWD/$SOURCE/tensorflow/lite/testing/split.h" "$CWD/$INCS/tensorflow/lite/testing/split.h"
cp "$CWD/$SOURCE/tensorflow/lite/schema/schema_generated.h" "$CWD/$INCS/tensorflow/lite/schema/schema_generated.h"
cp "$CWD/$SOURCE/tensorflow/lite/schema/builtin_ops_header/generator.h" "$CWD/$INCS/tensorflow/lite/schema/builtin_ops_header/generator.h"
cp "$CWD/$SOURCE/tensorflow/lite/profiling/time.h" "$CWD/$INCS/tensorflow/lite/profiling/time.h"
cp "$CWD/$SOURCE/tensorflow/lite/profiling/profile_summarizer.h" "$CWD/$INCS/tensorflow/lite/profiling/profile_summarizer.h"
cp "$CWD/$SOURCE/tensorflow/lite/profiling/profile_buffer.h" "$CWD/$INCS/tensorflow/lite/profiling/profile_buffer.h"
cp "$CWD/$SOURCE/tensorflow/lite/profiling/profiler.h" "$CWD/$INCS/tensorflow/lite/profiling/profiler.h"
cp "$CWD/$SOURCE/tensorflow/lite/mutable_op_resolver.h" "$CWD/$INCS/tensorflow/lite/mutable_op_resolver.h"
cp "$CWD/$SOURCE/tensorflow/lite/util.h" "$CWD/$INCS/tensorflow/lite/util.h"
cp "$CWD/$SOURCE/tensorflow/lite/model.h" "$CWD/$INCS/tensorflow/lite/model.h"
cp "$CWD/$SOURCE/tensorflow/lite/delegates/nnapi/nnapi_delegate.h" "$CWD/$INCS/tensorflow/lite/delegates/nnapi/nnapi_delegate.h"
cp "$CWD/$SOURCE/tensorflow/lite/delegates/flex/delegate_data.h" "$CWD/$INCS/tensorflow/lite/delegates/flex/delegate_data.h"
cp "$CWD/$SOURCE/tensorflow/lite/delegates/flex/delegate.h" "$CWD/$INCS/tensorflow/lite/delegates/flex/delegate.h"
cp "$CWD/$SOURCE/tensorflow/lite/delegates/flex/buffer_map.h" "$CWD/$INCS/tensorflow/lite/delegates/flex/buffer_map.h"
cp "$CWD/$SOURCE/tensorflow/lite/delegates/flex/util.h" "$CWD/$INCS/tensorflow/lite/delegates/flex/util.h"
cp "$CWD/$SOURCE/tensorflow/lite/delegates/flex/kernel.h" "$CWD/$INCS/tensorflow/lite/delegates/flex/kernel.h"
cp "$CWD/$SOURCE/tensorflow/lite/delegates/flex/test_util.h" "$CWD/$INCS/tensorflow/lite/delegates/flex/test_util.h"
cp "$CWD/$SOURCE/tensorflow/lite/graph_info.h" "$CWD/$INCS/tensorflow/lite/graph_info.h"
cp "$CWD/$SOURCE/tensorflow/lite/optional_debug_tools.h" "$CWD/$INCS/tensorflow/lite/optional_debug_tools.h"
cp "$CWD/$SOURCE/tensorflow/lite/c/c_api_internal.h" "$CWD/$INCS/tensorflow/lite/c/c_api_internal.h"
cp "$CWD/$SOURCE/tensorflow/lite/c/builtin_op_data.h" "$CWD/$INCS/tensorflow/lite/c/builtin_op_data.h"
cp "$CWD/$SOURCE/tensorflow/lite/string.h" "$CWD/$INCS/tensorflow/lite/string.h"
